language: python
python:
  - "3.7"
install:
  - pip install .
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov-report=term --cov-config=.coveragerc --cov=fsetools/
after_success:
  - codecov
