# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog_0405_thermal_radiation_extreme.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(786, 401)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 310, 786, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.groupBox_in = QGroupBox(self.centralwidget)
        self.groupBox_in.setObjectName(u"groupBox_in")
        self.groupBox_in.setGeometry(QRect(370, 40, 201, 251))
        self.label_30 = QLabel(self.groupBox_in)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 75, 61, 21))
        self.label_30.setMinimumSize(QSize(0, 0))
        self.label_30.setMaximumSize(QSize(99999, 99999))
        self.label_30.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_24 = QLabel(self.groupBox_in)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 220, 61, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QSize(0, 0))
        self.label_24.setMaximumSize(QSize(99999, 99999))
        self.label_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_26 = QLabel(self.groupBox_in)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 145, 61, 21))
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QSize(0, 0))
        self.label_26.setMaximumSize(QSize(99999, 99999))
        self.label_26.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_in_receiver_location = QLineEdit(self.groupBox_in)
        self.lineEdit_in_receiver_location.setObjectName(u"lineEdit_in_receiver_location")
        self.lineEdit_in_receiver_location.setGeometry(QRect(70, 170, 121, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_receiver_location.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_receiver_location.setSizePolicy(sizePolicy)
        self.lineEdit_in_receiver_location.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_receiver_location.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_receiver_location.setBaseSize(QSize(0, 0))
        self.lineEdit_in_emitter_normal = QLineEdit(self.groupBox_in)
        self.lineEdit_in_emitter_normal.setObjectName(u"lineEdit_in_emitter_normal")
        self.lineEdit_in_emitter_normal.setGeometry(QRect(70, 145, 121, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_emitter_normal.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_emitter_normal.setSizePolicy(sizePolicy)
        self.lineEdit_in_emitter_normal.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_emitter_normal.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_emitter_normal.setBaseSize(QSize(0, 0))
        self.lineEdit_in_receiver_normal = QLineEdit(self.groupBox_in)
        self.lineEdit_in_receiver_normal.setObjectName(u"lineEdit_in_receiver_normal")
        self.lineEdit_in_receiver_normal.setGeometry(QRect(70, 195, 121, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_receiver_normal.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_receiver_normal.setSizePolicy(sizePolicy)
        self.lineEdit_in_receiver_normal.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_receiver_normal.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_receiver_normal.setBaseSize(QSize(0, 0))
        self.label_43 = QLabel(self.groupBox_in)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(140, 220, 40, 21))
        self.label_43.setMinimumSize(QSize(0, 0))
        self.label_43.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_Q = QLineEdit(self.groupBox_in)
        self.lineEdit_in_Q.setObjectName(u"lineEdit_in_Q")
        self.lineEdit_in_Q.setGeometry(QRect(70, 220, 61, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_Q.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_Q.setSizePolicy(sizePolicy)
        self.lineEdit_in_Q.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_Q.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_Q.setBaseSize(QSize(0, 0))
        self.label_27 = QLabel(self.groupBox_in)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 195, 61, 21))
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QSize(0, 0))
        self.label_27.setMaximumSize(QSize(99999, 99999))
        self.label_27.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_28 = QLabel(self.groupBox_in)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 170, 61, 21))
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QSize(0, 0))
        self.label_28.setMaximumSize(QSize(99999, 99999))
        self.label_28.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.plainTextEdit_in_emiter_xyz = QPlainTextEdit(self.groupBox_in)
        self.plainTextEdit_in_emiter_xyz.setObjectName(u"plainTextEdit_in_emiter_xyz")
        self.plainTextEdit_in_emiter_xyz.setGeometry(QRect(70, 25, 121, 116))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 15, 341, 285))
        self.label.setPixmap(QPixmap(u"../images/phi_calculator_extreme.png"))
        self.pushButton_calculate = QPushButton(self.centralwidget)
        self.pushButton_calculate.setObjectName(u"pushButton_calculate")
        self.pushButton_calculate.setGeometry(QRect(675, 330, 96, 24))
        self.groupBox_optionals = QGroupBox(self.centralwidget)
        self.groupBox_optionals.setObjectName(u"groupBox_optionals")
        self.groupBox_optionals.setGeometry(QRect(585, 40, 186, 86))
        self.lineEdit_in_emitter_points = QLineEdit(self.groupBox_optionals)
        self.lineEdit_in_emitter_points.setObjectName(u"lineEdit_in_emitter_points")
        self.lineEdit_in_emitter_points.setGeometry(QRect(70, 25, 60, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_emitter_points.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_emitter_points.setSizePolicy(sizePolicy)
        self.lineEdit_in_emitter_points.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_emitter_points.setMaximumSize(QSize(60, 16777215))
        self.label_14 = QLabel(self.groupBox_optionals)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 25, 61, 21))
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QSize(40, 0))
        self.label_14.setMaximumSize(QSize(16777215, 16777215))
        self.label_15 = QLabel(self.groupBox_optionals)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 50, 61, 21))
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QSize(40, 0))
        self.label_15.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_in_receiver_initial_temperature = QLineEdit(self.groupBox_optionals)
        self.lineEdit_in_receiver_initial_temperature.setObjectName(u"lineEdit_in_receiver_initial_temperature")
        self.lineEdit_in_receiver_initial_temperature.setGeometry(QRect(70, 50, 60, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_in_receiver_initial_temperature.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_receiver_initial_temperature.setSizePolicy(sizePolicy)
        self.lineEdit_in_receiver_initial_temperature.setMinimumSize(QSize(0, 0))
        self.lineEdit_in_receiver_initial_temperature.setMaximumSize(QSize(60, 16777215))
        self.label_45 = QLabel(self.groupBox_optionals)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(135, 50, 50, 21))
        self.pushButton_test = QPushButton(self.centralwidget)
        self.pushButton_test.setObjectName(u"pushButton_test")
        self.pushButton_test.setGeometry(QRect(15, 330, 96, 24))
        self.groupBox_out = QGroupBox(self.centralwidget)
        self.groupBox_out.setObjectName(u"groupBox_out")
        self.groupBox_out.setGeometry(QRect(585, 185, 186, 106))
        self.lineEdit_out_Phi = QLineEdit(self.groupBox_out)
        self.lineEdit_out_Phi.setObjectName(u"lineEdit_out_Phi")
        self.lineEdit_out_Phi.setGeometry(QRect(70, 50, 60, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_Phi.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Phi.setSizePolicy(sizePolicy)
        self.lineEdit_out_Phi.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_Phi.setMaximumSize(QSize(60, 16777215))
        self.lineEdit_out_q = QLineEdit(self.groupBox_out)
        self.lineEdit_out_q.setObjectName(u"lineEdit_out_q")
        self.lineEdit_out_q.setGeometry(QRect(70, 75, 60, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_q.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_q.setSizePolicy(sizePolicy)
        self.lineEdit_out_q.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_q.setMaximumSize(QSize(60, 16777215))
        self.label_out_Phi = QLabel(self.groupBox_out)
        self.label_out_Phi.setObjectName(u"label_out_Phi")
        self.label_out_Phi.setGeometry(QRect(10, 50, 40, 21))
        sizePolicy.setHeightForWidth(self.label_out_Phi.sizePolicy().hasHeightForWidth())
        self.label_out_Phi.setSizePolicy(sizePolicy)
        self.label_out_Phi.setMinimumSize(QSize(40, 0))
        self.label_out_Phi.setMaximumSize(QSize(40, 16777215))
        self.label_out_q = QLabel(self.groupBox_out)
        self.label_out_q.setObjectName(u"label_out_q")
        self.label_out_q.setGeometry(QRect(10, 75, 40, 21))
        sizePolicy.setHeightForWidth(self.label_out_q.sizePolicy().hasHeightForWidth())
        self.label_out_q.setSizePolicy(sizePolicy)
        self.label_out_q.setMinimumSize(QSize(20, 0))
        self.label_out_q.setMaximumSize(QSize(40, 16777215))
        self.label_out_q_unit = QLabel(self.groupBox_out)
        self.label_out_q_unit.setObjectName(u"label_out_q_unit")
        self.label_out_q_unit.setGeometry(QRect(135, 75, 50, 21))
        self.label_out_T = QLabel(self.groupBox_out)
        self.label_out_T.setObjectName(u"label_out_T")
        self.label_out_T.setGeometry(QRect(10, 25, 40, 21))
        sizePolicy.setHeightForWidth(self.label_out_T.sizePolicy().hasHeightForWidth())
        self.label_out_T.setSizePolicy(sizePolicy)
        self.label_out_T.setMinimumSize(QSize(40, 0))
        self.label_out_T.setMaximumSize(QSize(40, 16777215))
        self.lineEdit_out_T = QLineEdit(self.groupBox_out)
        self.lineEdit_out_T.setObjectName(u"lineEdit_out_T")
        self.lineEdit_out_T.setGeometry(QRect(70, 25, 60, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_T.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_T.setSizePolicy(sizePolicy)
        self.lineEdit_out_T.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_T.setMaximumSize(QSize(60, 16777215))
        self.label_out_T_unit = QLabel(self.groupBox_out)
        self.label_out_T_unit.setObjectName(u"label_out_T_unit")
        self.label_out_T_unit.setGeometry(QRect(135, 25, 50, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 786, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_in.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
#if QT_CONFIG(tooltip)
        self.label_30.setToolTip(QCoreApplication.translate("MainWindow", u"Vertices of emitter", None))
#endif // QT_CONFIG(tooltip)
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"XYZ", None))
#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("MainWindow", u"Heat flux of emitter", None))
#endif // QT_CONFIG(tooltip)
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Q", None))
#if QT_CONFIG(tooltip)
        self.label_26.setToolTip(QCoreApplication.translate("MainWindow", u"Emitter orientation (normal)", None))
#endif // QT_CONFIG(tooltip)
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>X<span style=\" vertical-align:sub;\">nE</span>, Y<span style=\" vertical-align:sub;\">nE</span>, Z<span style=\" vertical-align:sub;\">nE</span></p></body></html>", None))
        self.lineEdit_in_emitter_normal.setText("")
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"kW/m\u00b2", None))
#if QT_CONFIG(tooltip)
        self.label_27.setToolTip(QCoreApplication.translate("MainWindow", u"Receiver orientation (normal)", None))
#endif // QT_CONFIG(tooltip)
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>X<span style=\" vertical-align:sub;\">nR</span>, Y<span style=\" vertical-align:sub;\">nR</span>, Z<span style=\" vertical-align:sub;\">nR</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_28.setToolTip(QCoreApplication.translate("MainWindow", u"Receiver location", None))
#endif // QT_CONFIG(tooltip)
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>X<span style=\" vertical-align:sub;\">R</span>, Y<span style=\" vertical-align:sub;\">R</span>, Z<span style=\" vertical-align:sub;\">R</span></p></body></html>", None))
        self.label.setText("")
        self.pushButton_calculate.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.groupBox_optionals.setTitle(QCoreApplication.translate("MainWindow", u"Optional", None))
#if QT_CONFIG(tooltip)
        self.label_14.setToolTip(QCoreApplication.translate("MainWindow", u"Number of emitting points on emitter surface that the calculation will be based on", None))
#endif // QT_CONFIG(tooltip)
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"n. points", None))
#if QT_CONFIG(tooltip)
        self.label_15.setToolTip(QCoreApplication.translate("MainWindow", u"Receiver temperature (i.e. ambient temperature)", None))
#endif // QT_CONFIG(tooltip)
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"T receiver", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"K", None))
        self.pushButton_test.setText(QCoreApplication.translate("MainWindow", u"Example", None))
        self.groupBox_out.setTitle(QCoreApplication.translate("MainWindow", u"Outputs", None))
#if QT_CONFIG(tooltip)
        self.label_out_Phi.setToolTip(QCoreApplication.translate("MainWindow", u"Solved view factor", None))
#endif // QT_CONFIG(tooltip)
        self.label_out_Phi.setText(QCoreApplication.translate("MainWindow", u"\u03a6", None))
#if QT_CONFIG(tooltip)
        self.label_out_q.setToolTip(QCoreApplication.translate("MainWindow", u"Solved heat flux at receiver", None))
#endif // QT_CONFIG(tooltip)
        self.label_out_q.setText(QCoreApplication.translate("MainWindow", u"q", None))
        self.label_out_q_unit.setText(QCoreApplication.translate("MainWindow", u"kW/m\u00b2", None))
#if QT_CONFIG(tooltip)
        self.label_out_T.setToolTip(QCoreApplication.translate("MainWindow", u"Solved temperature at receiver", None))
#endif // QT_CONFIG(tooltip)
        self.label_out_T.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.label_out_T_unit.setText(QCoreApplication.translate("MainWindow", u"K", None))
    # retranslateUi

