# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog_0403_br187_parallel_complex.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(826, 651)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 15, 796, 566))
        self.label.setPixmap(QPixmap(u"../images/0401_parallel_simple_794_560.png"))
        self.groupBox_in = QGroupBox(self.centralwidget)
        self.groupBox_in.setObjectName(u"groupBox_in")
        self.groupBox_in.setGeometry(QRect(415, 245, 396, 181))
        self.label_unit_S_or_UA = QLabel(self.groupBox_in)
        self.label_unit_S_or_UA.setObjectName(u"label_unit_S_or_UA")
        self.label_unit_S_or_UA.setGeometry(QRect(315, 150, 40, 21))
        self.label_unit_S_or_UA.setMinimumSize(QSize(0, 0))
        self.label_unit_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.label_38 = QLabel(self.groupBox_in)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(315, 125, 40, 21))
        self.label_38.setMinimumSize(QSize(0, 0))
        self.label_38.setMaximumSize(QSize(16777215, 16777215))
        self.label_39 = QLabel(self.groupBox_in)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(315, 50, 40, 21))
        self.label_39.setMinimumSize(QSize(0, 0))
        self.label_39.setMaximumSize(QSize(16777215, 16777215))
        self.label_40 = QLabel(self.groupBox_in)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(315, 25, 40, 21))
        self.label_40.setMinimumSize(QSize(0, 0))
        self.label_40.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_W = QLineEdit(self.groupBox_in)
        self.lineEdit_W.setObjectName(u"lineEdit_W")
        self.lineEdit_W.setGeometry(QRect(210, 25, 91, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_W.sizePolicy().hasHeightForWidth())
        self.lineEdit_W.setSizePolicy(sizePolicy)
        self.lineEdit_W.setMinimumSize(QSize(0, 0))
        self.lineEdit_W.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_W.setBaseSize(QSize(0, 0))
        self.lineEdit_H = QLineEdit(self.groupBox_in)
        self.lineEdit_H.setObjectName(u"lineEdit_H")
        self.lineEdit_H.setGeometry(QRect(210, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_H.sizePolicy().hasHeightForWidth())
        self.lineEdit_H.setSizePolicy(sizePolicy)
        self.lineEdit_H.setMinimumSize(QSize(0, 0))
        self.lineEdit_H.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_H.setBaseSize(QSize(0, 0))
        self.lineEdit_S_or_UA = QLineEdit(self.groupBox_in)
        self.lineEdit_S_or_UA.setObjectName(u"lineEdit_S_or_UA")
        self.lineEdit_S_or_UA.setGeometry(QRect(210, 150, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_S_or_UA.setMinimumSize(QSize(0, 0))
        self.lineEdit_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_S_or_UA.setBaseSize(QSize(0, 0))
        self.lineEdit_Q = QLineEdit(self.groupBox_in)
        self.lineEdit_Q.setObjectName(u"lineEdit_Q")
        self.lineEdit_Q.setGeometry(QRect(210, 125, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_Q.sizePolicy().hasHeightForWidth())
        self.lineEdit_Q.setSizePolicy(sizePolicy)
        self.lineEdit_Q.setMinimumSize(QSize(0, 0))
        self.lineEdit_Q.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_Q.setBaseSize(QSize(0, 0))
        self.label_24 = QLabel(self.groupBox_in)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 125, 181, 21))
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QSize(0, 0))
        self.label_24.setMaximumSize(QSize(99999, 30))
        self.label_28 = QLabel(self.groupBox_in)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 50, 181, 21))
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QSize(0, 0))
        self.label_28.setMaximumSize(QSize(99999, 30))
        self.label_41 = QLabel(self.groupBox_in)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 25, 181, 21))
        self.label_41.setMinimumSize(QSize(0, 0))
        self.label_41.setMaximumSize(QSize(99999, 30))
        self.label_42 = QLabel(self.groupBox_in)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 75, 181, 21))
        self.label_42.setMinimumSize(QSize(0, 0))
        self.label_42.setMaximumSize(QSize(99999, 30))
        self.label_43 = QLabel(self.groupBox_in)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 100, 181, 21))
        self.label_43.setMinimumSize(QSize(0, 0))
        self.label_43.setMaximumSize(QSize(99999, 30))
        self.lineEdit_w = QLineEdit(self.groupBox_in)
        self.lineEdit_w.setObjectName(u"lineEdit_w")
        self.lineEdit_w.setGeometry(QRect(210, 75, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_w.sizePolicy().hasHeightForWidth())
        self.lineEdit_w.setSizePolicy(sizePolicy)
        self.lineEdit_w.setMinimumSize(QSize(0, 0))
        self.lineEdit_w.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_w.setBaseSize(QSize(0, 0))
        self.lineEdit_h = QLineEdit(self.groupBox_in)
        self.lineEdit_h.setObjectName(u"lineEdit_h")
        self.lineEdit_h.setGeometry(QRect(210, 100, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_h.sizePolicy().hasHeightForWidth())
        self.lineEdit_h.setSizePolicy(sizePolicy)
        self.lineEdit_h.setMinimumSize(QSize(0, 0))
        self.lineEdit_h.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_h.setBaseSize(QSize(0, 0))
        self.label_44 = QLabel(self.groupBox_in)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(315, 75, 40, 21))
        self.label_44.setMinimumSize(QSize(0, 0))
        self.label_44.setMaximumSize(QSize(16777215, 16777215))
        self.label_45 = QLabel(self.groupBox_in)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(315, 100, 40, 21))
        self.label_45.setMinimumSize(QSize(0, 0))
        self.label_45.setMaximumSize(QSize(16777215, 16777215))
        self.comboBox_S_or_UA = QComboBox(self.groupBox_in)
        self.comboBox_S_or_UA.addItem("")
        self.comboBox_S_or_UA.addItem("")
        self.comboBox_S_or_UA.setObjectName(u"comboBox_S_or_UA")
        self.comboBox_S_or_UA.setGeometry(QRect(10, 150, 181, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.comboBox_S_or_UA.sizePolicy().hasHeightForWidth())
        self.comboBox_S_or_UA.setSizePolicy(sizePolicy1)
        self.comboBox_S_or_UA.setMinimumSize(QSize(0, 0))
        self.comboBox_S_or_UA.setMaximumSize(QSize(9999, 9999))
        self.pushButton_calculate = QPushButton(self.centralwidget)
        self.pushButton_calculate.setObjectName(u"pushButton_calculate")
        self.pushButton_calculate.setGeometry(QRect(715, 555, 96, 26))
        self.pushButton_test = QPushButton(self.centralwidget)
        self.pushButton_test.setObjectName(u"pushButton_test")
        self.pushButton_test.setGeometry(QRect(600, 555, 96, 26))
        self.groupBox_out = QGroupBox(self.centralwidget)
        self.groupBox_out.setObjectName(u"groupBox_out")
        self.groupBox_out.setGeometry(QRect(415, 430, 396, 106))
        self.lineEdit_out_Phi = QLineEdit(self.groupBox_out)
        self.lineEdit_out_Phi.setObjectName(u"lineEdit_out_Phi")
        self.lineEdit_out_Phi.setGeometry(QRect(210, 25, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_Phi.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Phi.setSizePolicy(sizePolicy)
        self.lineEdit_out_Phi.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_Phi.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_out_q = QLineEdit(self.groupBox_out)
        self.lineEdit_out_q.setObjectName(u"lineEdit_out_q")
        self.lineEdit_out_q.setGeometry(QRect(210, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_q.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_q.setSizePolicy(sizePolicy)
        self.lineEdit_out_q.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_q.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_out_S_or_UA = QLineEdit(self.groupBox_out)
        self.lineEdit_out_S_or_UA.setObjectName(u"lineEdit_out_S_or_UA")
        self.lineEdit_out_S_or_UA.setGeometry(QRect(210, 75, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_out_S_or_UA.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_Phi = QLabel(self.groupBox_out)
        self.label_out_Phi.setObjectName(u"label_out_Phi")
        self.label_out_Phi.setGeometry(QRect(10, 25, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_Phi.sizePolicy().hasHeightForWidth())
        self.label_out_Phi.setSizePolicy(sizePolicy)
        self.label_out_Phi.setMinimumSize(QSize(40, 0))
        self.label_out_Phi.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_q = QLabel(self.groupBox_out)
        self.label_out_q.setObjectName(u"label_out_q")
        self.label_out_q.setGeometry(QRect(10, 50, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_q.sizePolicy().hasHeightForWidth())
        self.label_out_q.setSizePolicy(sizePolicy)
        self.label_out_q.setMinimumSize(QSize(20, 0))
        self.label_out_q.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_S_or_UA = QLabel(self.groupBox_out)
        self.label_out_S_or_UA.setObjectName(u"label_out_S_or_UA")
        self.label_out_S_or_UA.setGeometry(QRect(10, 75, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.label_out_S_or_UA.setSizePolicy(sizePolicy)
        self.label_out_S_or_UA.setMinimumSize(QSize(20, 0))
        self.label_out_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_q_unit = QLabel(self.groupBox_out)
        self.label_out_q_unit.setObjectName(u"label_out_q_unit")
        self.label_out_q_unit.setGeometry(QRect(315, 50, 50, 21))
        self.label_out_S_or_UA_unit = QLabel(self.groupBox_out)
        self.label_out_S_or_UA_unit.setObjectName(u"label_out_S_or_UA_unit")
        self.label_out_S_or_UA_unit.setGeometry(QRect(315, 75, 50, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 826, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.lineEdit_W, self.lineEdit_H)
        QWidget.setTabOrder(self.lineEdit_H, self.lineEdit_w)
        QWidget.setTabOrder(self.lineEdit_w, self.lineEdit_h)
        QWidget.setTabOrder(self.lineEdit_h, self.lineEdit_Q)
        QWidget.setTabOrder(self.lineEdit_Q, self.lineEdit_S_or_UA)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.groupBox_in.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.label_unit_S_or_UA.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"kW/m\u00b2", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"m", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_W.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_W.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_H.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_H.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_S_or_UA.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_S_or_UA.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_Q.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float. {'Reduced fire load': 84, 'Normal fire load': 168}.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_Q.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float. {'Reduced fire load': 84, 'Normal fire load': 168}.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("MainWindow", u"Heat flux of emitter.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_24.setStatusTip(QCoreApplication.translate("MainWindow", u"Heat flux of emitter.", None))
#endif // QT_CONFIG(statustip)
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Q, Emitter Heat Flux", None))
#if QT_CONFIG(tooltip)
        self.label_28.setToolTip(QCoreApplication.translate("MainWindow", u"Height of emitter.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_28.setStatusTip(QCoreApplication.translate("MainWindow", u"Height of emitter.", None))
#endif // QT_CONFIG(statustip)
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"H, Emitter Height", None))
#if QT_CONFIG(tooltip)
        self.label_41.setToolTip(QCoreApplication.translate("MainWindow", u"Width of emitter.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_41.setStatusTip(QCoreApplication.translate("MainWindow", u"Width of emitter.", None))
#endif // QT_CONFIG(statustip)
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"W, Emitter Width", None))
#if QT_CONFIG(tooltip)
        self.label_42.setToolTip(QCoreApplication.translate("MainWindow", u"Receiver location 1.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_42.setStatusTip(QCoreApplication.translate("MainWindow", u"Receiver location 1.", None))
#endif // QT_CONFIG(statustip)
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"w, Receiver Location", None))
#if QT_CONFIG(tooltip)
        self.label_43.setToolTip(QCoreApplication.translate("MainWindow", u"Receiver location 2.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_43.setStatusTip(QCoreApplication.translate("MainWindow", u"Receiver location 2.", None))
#endif // QT_CONFIG(statustip)
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"h, Receiver Location", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_w.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_w.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_h.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_h.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.comboBox_S_or_UA.setItemText(0, QCoreApplication.translate("MainWindow", u"\u00bdS, emitter to boundary", None))
        self.comboBox_S_or_UA.setItemText(1, QCoreApplication.translate("MainWindow", u"Allowed unprotected area", None))

#if QT_CONFIG(tooltip)
        self.comboBox_S_or_UA.setToolTip(QCoreApplication.translate("MainWindow", u"This should be dealt within gui logic", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.comboBox_S_or_UA.setStatusTip(QCoreApplication.translate("MainWindow", u"This should be dealt within gui logic", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.pushButton_calculate.setToolTip(QCoreApplication.translate("MainWindow", u"Calculate or press Enter.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_calculate.setStatusTip(QCoreApplication.translate("MainWindow", u"Calculate or press Enter.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_calculate.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
#if QT_CONFIG(tooltip)
        self.pushButton_test.setToolTip(QCoreApplication.translate("MainWindow", u"Generate example input parameters.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_test.setStatusTip(QCoreApplication.translate("MainWindow", u"Generate example input parameters.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_test.setText(QCoreApplication.translate("MainWindow", u"Example", None))
        self.groupBox_out.setTitle(QCoreApplication.translate("MainWindow", u"Outputs", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_out_Phi.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_out_Phi.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_out_q.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_out_q.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_out_S_or_UA.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_out_S_or_UA.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.label_out_Phi.setToolTip(QCoreApplication.translate("MainWindow", u"Solved view factor.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_Phi.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved view factor.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_Phi.setText(QCoreApplication.translate("MainWindow", u"\u03a6, view factor", None))
#if QT_CONFIG(tooltip)
        self.label_out_q.setToolTip(QCoreApplication.translate("MainWindow", u"Solved heat flux at receiver surface when 100 % unprotected.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_q.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved heat flux at receiver surface when 100 % unprotected.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_q.setText(QCoreApplication.translate("MainWindow", u"q, receiver heat flux", None))
#if QT_CONFIG(tooltip)
        self.label_out_S_or_UA.setToolTip(QCoreApplication.translate("MainWindow", u"Solved maximum permissible unprotected area.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_S_or_UA.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved maximum permissible unprotected area.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_S_or_UA.setText(QCoreApplication.translate("MainWindow", u"Max. unprotected area", None))
        self.label_out_q_unit.setText(QCoreApplication.translate("MainWindow", u"kW/m\u00b2", None))
        self.label_out_S_or_UA_unit.setText(QCoreApplication.translate("MainWindow", u"%", None))
    # retranslateUi

