# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0403_br187_parallel_complex.ui',
# licensing of '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0403_br187_parallel_complex.ui' applies.
#
# Created: Thu Feb 20 22:28:39 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 15, 796, 566))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/0401_parallel_simple_794_560.png"))
        self.label.setObjectName("label")
        self.groupBox_in = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_in.setGeometry(QtCore.QRect(415, 245, 396, 181))
        self.groupBox_in.setObjectName("groupBox_in")
        self.label_unit_S_or_UA = QtWidgets.QLabel(self.groupBox_in)
        self.label_unit_S_or_UA.setGeometry(QtCore.QRect(315, 150, 40, 21))
        self.label_unit_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.label_unit_S_or_UA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_unit_S_or_UA.setObjectName("label_unit_S_or_UA")
        self.label_38 = QtWidgets.QLabel(self.groupBox_in)
        self.label_38.setGeometry(QtCore.QRect(315, 125, 40, 21))
        self.label_38.setMinimumSize(QtCore.QSize(0, 0))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_in)
        self.label_39.setGeometry(QtCore.QRect(315, 50, 40, 21))
        self.label_39.setMinimumSize(QtCore.QSize(0, 0))
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_in)
        self.label_40.setGeometry(QtCore.QRect(315, 25, 40, 21))
        self.label_40.setMinimumSize(QtCore.QSize(0, 0))
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_40.setObjectName("label_40")
        self.lineEdit_W = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_W.setGeometry(QtCore.QRect(210, 25, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_W.sizePolicy().hasHeightForWidth())
        self.lineEdit_W.setSizePolicy(sizePolicy)
        self.lineEdit_W.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_W.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_W.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_W.setObjectName("lineEdit_W")
        self.lineEdit_H = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_H.setGeometry(QtCore.QRect(210, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_H.sizePolicy().hasHeightForWidth())
        self.lineEdit_H.setSizePolicy(sizePolicy)
        self.lineEdit_H.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_H.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_H.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_H.setObjectName("lineEdit_H")
        self.lineEdit_S_or_UA = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_S_or_UA.setGeometry(QtCore.QRect(210, 150, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_S_or_UA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_S_or_UA.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_S_or_UA.setObjectName("lineEdit_S_or_UA")
        self.lineEdit_Q = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_Q.setGeometry(QtCore.QRect(210, 125, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Q.sizePolicy().hasHeightForWidth())
        self.lineEdit_Q.setSizePolicy(sizePolicy)
        self.lineEdit_Q.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_Q.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Q.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_Q.setObjectName("lineEdit_Q")
        self.label_24 = QtWidgets.QLabel(self.groupBox_in)
        self.label_24.setGeometry(QtCore.QRect(10, 125, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        self.label_24.setMaximumSize(QtCore.QSize(99999, 30))
        self.label_24.setObjectName("label_24")
        self.label_28 = QtWidgets.QLabel(self.groupBox_in)
        self.label_28.setGeometry(QtCore.QRect(10, 50, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_28.setMaximumSize(QtCore.QSize(99999, 30))
        self.label_28.setObjectName("label_28")
        self.label_41 = QtWidgets.QLabel(self.groupBox_in)
        self.label_41.setGeometry(QtCore.QRect(10, 25, 181, 21))
        self.label_41.setMinimumSize(QtCore.QSize(0, 0))
        self.label_41.setMaximumSize(QtCore.QSize(99999, 30))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_in)
        self.label_42.setGeometry(QtCore.QRect(10, 75, 181, 21))
        self.label_42.setMinimumSize(QtCore.QSize(0, 0))
        self.label_42.setMaximumSize(QtCore.QSize(99999, 30))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_in)
        self.label_43.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.label_43.setMinimumSize(QtCore.QSize(0, 0))
        self.label_43.setMaximumSize(QtCore.QSize(99999, 30))
        self.label_43.setObjectName("label_43")
        self.lineEdit_w = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_w.setGeometry(QtCore.QRect(210, 75, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_w.sizePolicy().hasHeightForWidth())
        self.lineEdit_w.setSizePolicy(sizePolicy)
        self.lineEdit_w.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_w.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_w.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_w.setObjectName("lineEdit_w")
        self.lineEdit_h = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_h.setGeometry(QtCore.QRect(210, 100, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_h.sizePolicy().hasHeightForWidth())
        self.lineEdit_h.setSizePolicy(sizePolicy)
        self.lineEdit_h.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_h.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_h.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.label_44 = QtWidgets.QLabel(self.groupBox_in)
        self.label_44.setGeometry(QtCore.QRect(315, 75, 40, 21))
        self.label_44.setMinimumSize(QtCore.QSize(0, 0))
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_in)
        self.label_45.setGeometry(QtCore.QRect(315, 100, 40, 21))
        self.label_45.setMinimumSize(QtCore.QSize(0, 0))
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_45.setObjectName("label_45")
        self.comboBox_S_or_UA = QtWidgets.QComboBox(self.groupBox_in)
        self.comboBox_S_or_UA.setGeometry(QtCore.QRect(10, 150, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_S_or_UA.sizePolicy().hasHeightForWidth())
        self.comboBox_S_or_UA.setSizePolicy(sizePolicy)
        self.comboBox_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_S_or_UA.setMaximumSize(QtCore.QSize(9999, 9999))
        self.comboBox_S_or_UA.setObjectName("comboBox_S_or_UA")
        self.comboBox_S_or_UA.addItem("")
        self.comboBox_S_or_UA.addItem("")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(715, 555, 96, 26))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_test.setGeometry(QtCore.QRect(600, 555, 96, 26))
        self.pushButton_test.setObjectName("pushButton_test")
        self.groupBox_out = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_out.setGeometry(QtCore.QRect(415, 430, 396, 106))
        self.groupBox_out.setObjectName("groupBox_out")
        self.lineEdit_out_Phi = QtWidgets.QLineEdit(self.groupBox_out)
        self.lineEdit_out_Phi.setGeometry(QtCore.QRect(210, 25, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_Phi.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Phi.setSizePolicy(sizePolicy)
        self.lineEdit_out_Phi.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_Phi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_out_Phi.setObjectName("lineEdit_out_Phi")
        self.lineEdit_out_q = QtWidgets.QLineEdit(self.groupBox_out)
        self.lineEdit_out_q.setGeometry(QtCore.QRect(210, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_q.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_q.setSizePolicy(sizePolicy)
        self.lineEdit_out_q.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_q.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_out_q.setObjectName("lineEdit_out_q")
        self.lineEdit_out_S_or_UA = QtWidgets.QLineEdit(self.groupBox_out)
        self.lineEdit_out_S_or_UA.setGeometry(QtCore.QRect(210, 75, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_out_S_or_UA.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_S_or_UA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_out_S_or_UA.setObjectName("lineEdit_out_S_or_UA")
        self.label_out_Phi = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_Phi.setGeometry(QtCore.QRect(10, 25, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_Phi.sizePolicy().hasHeightForWidth())
        self.label_out_Phi.setSizePolicy(sizePolicy)
        self.label_out_Phi.setMinimumSize(QtCore.QSize(40, 0))
        self.label_out_Phi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_out_Phi.setObjectName("label_out_Phi")
        self.label_out_q = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_q.setGeometry(QtCore.QRect(10, 50, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_q.sizePolicy().hasHeightForWidth())
        self.label_out_q.setSizePolicy(sizePolicy)
        self.label_out_q.setMinimumSize(QtCore.QSize(20, 0))
        self.label_out_q.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_out_q.setObjectName("label_out_q")
        self.label_out_S_or_UA = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_S_or_UA.setGeometry(QtCore.QRect(10, 75, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.label_out_S_or_UA.setSizePolicy(sizePolicy)
        self.label_out_S_or_UA.setMinimumSize(QtCore.QSize(20, 0))
        self.label_out_S_or_UA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_out_S_or_UA.setObjectName("label_out_S_or_UA")
        self.label_out_q_unit = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_q_unit.setGeometry(QtCore.QRect(315, 50, 50, 21))
        self.label_out_q_unit.setObjectName("label_out_q_unit")
        self.label_out_S_or_UA_unit = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_S_or_UA_unit.setGeometry(QtCore.QRect(315, 75, 50, 21))
        self.label_out_S_or_UA_unit.setObjectName("label_out_S_or_UA_unit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_W, self.lineEdit_H)
        MainWindow.setTabOrder(self.lineEdit_H, self.lineEdit_w)
        MainWindow.setTabOrder(self.lineEdit_w, self.lineEdit_h)
        MainWindow.setTabOrder(self.lineEdit_h, self.lineEdit_Q)
        MainWindow.setTabOrder(self.lineEdit_Q, self.lineEdit_S_or_UA)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_in.setTitle(QtWidgets.QApplication.translate("MainWindow", "Inputs", None, -1))
        self.label_unit_S_or_UA.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "kW/m²", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.lineEdit_W.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_W.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_H.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_H.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_S_or_UA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_S_or_UA.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_Q.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float. {\'Reduced fire load\': 84, \'Normal fire load\': 168}.", None, -1))
        self.lineEdit_Q.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float. {\'Reduced fire load\': 84, \'Normal fire load\': 168}.", None, -1))
        self.label_24.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Heat flux of emitter.", None, -1))
        self.label_24.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Heat flux of emitter.", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Q, Emitter Heat Flux", None, -1))
        self.label_28.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Height of emitter.", None, -1))
        self.label_28.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Height of emitter.", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "H, Emitter Height", None, -1))
        self.label_41.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Width of emitter.", None, -1))
        self.label_41.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Width of emitter.", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "W, Emitter Width", None, -1))
        self.label_42.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Receiver location 1.", None, -1))
        self.label_42.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Receiver location 1.", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "w, Receiver Location", None, -1))
        self.label_43.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Receiver location 2.", None, -1))
        self.label_43.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Receiver location 2.", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "h, Receiver Location", None, -1))
        self.lineEdit_w.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_w.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_h.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_h.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.comboBox_S_or_UA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "This should be dealt within gui logic", None, -1))
        self.comboBox_S_or_UA.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "This should be dealt within gui logic", None, -1))
        self.comboBox_S_or_UA.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "½S, emitter to boundary", None, -1))
        self.comboBox_S_or_UA.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Allowed unprotected area", None, -1))
        self.pushButton_calculate.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Calculate or press Enter.", None, -1))
        self.pushButton_calculate.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Calculate or press Enter.", None, -1))
        self.pushButton_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.pushButton_test.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Generate example input parameters.", None, -1))
        self.pushButton_test.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Generate example input parameters.", None, -1))
        self.pushButton_test.setText(QtWidgets.QApplication.translate("MainWindow", "Example", None, -1))
        self.groupBox_out.setTitle(QtWidgets.QApplication.translate("MainWindow", "Outputs", None, -1))
        self.lineEdit_out_Phi.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_out_Phi.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_out_q.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_out_q.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_out_S_or_UA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_out_S_or_UA.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.label_out_Phi.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved view factor.", None, -1))
        self.label_out_Phi.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Solved view factor.", None, -1))
        self.label_out_Phi.setText(QtWidgets.QApplication.translate("MainWindow", "Φ, view factor", None, -1))
        self.label_out_q.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved heat flux at receiver surface when 100 % unprotected.", None, -1))
        self.label_out_q.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Solved heat flux at receiver surface when 100 % unprotected.", None, -1))
        self.label_out_q.setText(QtWidgets.QApplication.translate("MainWindow", "q, receiver heat flux", None, -1))
        self.label_out_S_or_UA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved maximum permissible unprotected area.", None, -1))
        self.label_out_S_or_UA.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Solved maximum permissible unprotected area.", None, -1))
        self.label_out_S_or_UA.setText(QtWidgets.QApplication.translate("MainWindow", "Max. unprotected area", None, -1))
        self.label_out_q_unit.setText(QtWidgets.QApplication.translate("MainWindow", "kW/m²", None, -1))
        self.label_out_S_or_UA_unit.setText(QtWidgets.QApplication.translate("MainWindow", "%", None, -1))

