# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0601_naming_convention.ui',
# licensing of '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0601_naming_convention.ui' applies.
#
# Created: Thu Feb 20 22:28:39 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 356)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(15, 15, 361, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_1_date = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1_date.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_1_date.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_1_date.setObjectName("lineEdit_1_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_date)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboBox_2_revision = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2_revision.setMinimumSize(QtCore.QSize(0, 21))
        self.comboBox_2_revision.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_2_revision.setObjectName("comboBox_2_revision")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.comboBox_2_revision.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2_revision)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(121, 21))
        self.label_14.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_3_project_no = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3_project_no.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_3_project_no.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_3_project_no.setObjectName("lineEdit_3_project_no")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3_project_no)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_4_project_stage = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4_project_stage.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_4_project_stage.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_4_project_stage.setObjectName("lineEdit_4_project_stage")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4_project_stage)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_19.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.comboBox_6_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_6_type.setMinimumSize(QtCore.QSize(0, 21))
        self.comboBox_6_type.setObjectName("comboBox_6_type")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.comboBox_6_type.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_6_type)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.comboBox_7_security_status = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_7_security_status.setMinimumSize(QtCore.QSize(0, 21))
        self.comboBox_7_security_status.setObjectName("comboBox_7_security_status")
        self.comboBox_7_security_status.addItem("")
        self.comboBox_7_security_status.addItem("")
        self.comboBox_7_security_status.addItem("")
        self.comboBox_7_security_status.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_7_security_status)
        self.lineEdit_5_title = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5_title.setMinimumSize(QtCore.QSize(200, 21))
        self.lineEdit_5_title.setObjectName("lineEdit_5_title")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5_title)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.checkBox_replace_spaces = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_replace_spaces.setObjectName("checkBox_replace_spaces")
        self.verticalLayout.addWidget(self.checkBox_replace_spaces)
        self.lineEdit_out_result = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_out_result.setObjectName("lineEdit_out_result")
        self.verticalLayout.addWidget(self.lineEdit_out_result)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_copy = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.horizontalLayout_2.addWidget(self.pushButton_copy)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_16.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Date in YYMMDD (i.e. 201231) or YYYYMMDD (i.e. 20201231) format.", None, -1))
        self.label_16.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Date in YYMMDD (i.e. 201231) or YYYYMMDD (i.e. 20201231) format.", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.lineEdit_1_date.setText(QtWidgets.QApplication.translate("MainWindow", "20151021", None, -1))
        self.label_15.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Revision indicator.", None, -1))
        self.label_15.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Revision indicator.", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Revision", None, -1))
        self.comboBox_2_revision.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Q00: First issue for internal review", None, -1))
        self.comboBox_2_revision.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Q01: Reviewer\'s comments", None, -1))
        self.comboBox_2_revision.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Q02: Authoriser\'s comments", None, -1))
        self.comboBox_2_revision.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "D00: First issue to others for comment", None, -1))
        self.comboBox_2_revision.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "D01: Sub-sequent external reviews", None, -1))
        self.comboBox_2_revision.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "R00: First issue", None, -1))
        self.comboBox_2_revision.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "R01: Second issue", None, -1))
        self.label_14.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Project number.", None, -1))
        self.label_14.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Project number.", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Project No.", None, -1))
        self.lineEdit_3_project_no.setText(QtWidgets.QApplication.translate("MainWindow", "OX20001", None, -1))
        self.label_17.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Project stage.", None, -1))
        self.label_17.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Project stage.", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Project Stage", None, -1))
        self.lineEdit_4_project_stage.setText(QtWidgets.QApplication.translate("MainWindow", "WP1", None, -1))
        self.label_18.setToolTip(QtWidgets.QApplication.translate("MainWindow", "File title in plain English.", None, -1))
        self.label_18.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "File title in plain English.", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "File Title", None, -1))
        self.label_19.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Document type.", None, -1))
        self.label_19.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Document type.", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Document Type", None, -1))
        self.comboBox_6_type.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "GA: General admin", None, -1))
        self.comboBox_6_type.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "MD: Marketing", None, -1))
        self.comboBox_6_type.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "FP: Fee proposal", None, -1))
        self.comboBox_6_type.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "LT: Letter", None, -1))
        self.comboBox_6_type.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "DN: Design note", None, -1))
        self.comboBox_6_type.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "OF: Outline strategy", None, -1))
        self.comboBox_6_type.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "DF: Detailed strategy", None, -1))
        self.comboBox_6_type.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "RF: Retrospective strategy", None, -1))
        self.comboBox_6_type.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "FA: Fire risk assessment", None, -1))
        self.comboBox_6_type.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "FS: Fire survey report", None, -1))
        self.comboBox_6_type.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "FN: File note", None, -1))
        self.comboBox_6_type.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "MN: Meeting notes", None, -1))
        self.comboBox_6_type.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "CS: Calculation sheet", None, -1))
        self.comboBox_6_type.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "SK: Sketch", None, -1))
        self.comboBox_6_type.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "DW: Drawing", None, -1))
        self.comboBox_6_type.setItemText(15, QtWidgets.QApplication.translate("MainWindow", "XO: Expert opinion", None, -1))
        self.label_20.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Security status.", None, -1))
        self.label_20.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Security status.", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Security Status", None, -1))
        self.comboBox_7_security_status.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "CIC: Commercial in confidence", None, -1))
        self.comboBox_7_security_status.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "WPC: Without prejudice and confidential", None, -1))
        self.comboBox_7_security_status.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "SDS: Secure document", None, -1))
        self.comboBox_7_security_status.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "FID: Free issue document (no security status)", None, -1))
        self.lineEdit_5_title.setText(QtWidgets.QApplication.translate("MainWindow", "Outline fire strategy report", None, -1))
        self.checkBox_replace_spaces.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Replace all spaces in the file name to underscore `_`.", None, -1))
        self.checkBox_replace_spaces.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Replace all spaces in the file name to underscore `_`.", None, -1))
        self.checkBox_replace_spaces.setText(QtWidgets.QApplication.translate("MainWindow", "Replace Spaces with Underscore", None, -1))
        self.lineEdit_out_result.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Composed file name.", None, -1))
        self.lineEdit_out_result.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Composed file name.", None, -1))
        self.pushButton_copy.setText(QtWidgets.QApplication.translate("MainWindow", "Copy File Name (Press Enter)", None, -1))

