# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog_0401_br187_parallel_simple.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(826, 651)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(15, 15, 796, 566))
        self.label.setPixmap(QPixmap(u"../images/0401_parallel_simple_794_560.png"))
        self.groupBox_in = QGroupBox(self.centralwidget)
        self.groupBox_in.setObjectName(u"groupBox_in")
        self.groupBox_in.setEnabled(True)
        self.groupBox_in.setGeometry(QRect(415, 295, 396, 131))
        self.label_unit_S_or_UA = QLabel(self.groupBox_in)
        self.label_unit_S_or_UA.setObjectName(u"label_unit_S_or_UA")
        self.label_unit_S_or_UA.setGeometry(QRect(315, 100, 40, 21))
        self.label_unit_S_or_UA.setMinimumSize(QSize(0, 0))
        self.label_unit_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.label_34 = QLabel(self.groupBox_in)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(315, 75, 40, 21))
        self.label_34.setMinimumSize(QSize(0, 0))
        self.label_34.setMaximumSize(QSize(16777215, 16777215))
        self.label_33 = QLabel(self.groupBox_in)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(315, 50, 40, 21))
        self.label_33.setMinimumSize(QSize(0, 0))
        self.label_33.setMaximumSize(QSize(16777215, 16777215))
        self.label_32 = QLabel(self.groupBox_in)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(315, 25, 40, 21))
        self.label_32.setMinimumSize(QSize(0, 0))
        self.label_32.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_W = QLineEdit(self.groupBox_in)
        self.lineEdit_W.setObjectName(u"lineEdit_W")
        self.lineEdit_W.setGeometry(QRect(210, 25, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_W.sizePolicy().hasHeightForWidth())
        self.lineEdit_W.setSizePolicy(sizePolicy)
        self.lineEdit_W.setMinimumSize(QSize(0, 0))
        self.lineEdit_W.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_W.setBaseSize(QSize(0, 0))
        self.lineEdit_W.setMouseTracking(True)
        self.lineEdit_H = QLineEdit(self.groupBox_in)
        self.lineEdit_H.setObjectName(u"lineEdit_H")
        self.lineEdit_H.setGeometry(QRect(210, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_H.sizePolicy().hasHeightForWidth())
        self.lineEdit_H.setSizePolicy(sizePolicy)
        self.lineEdit_H.setMinimumSize(QSize(0, 0))
        self.lineEdit_H.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_H.setBaseSize(QSize(0, 0))
        self.lineEdit_S_or_UA = QLineEdit(self.groupBox_in)
        self.lineEdit_S_or_UA.setObjectName(u"lineEdit_S_or_UA")
        self.lineEdit_S_or_UA.setGeometry(QRect(210, 100, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_S_or_UA.setMinimumSize(QSize(0, 0))
        self.lineEdit_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_S_or_UA.setBaseSize(QSize(0, 0))
        self.lineEdit_Q = QLineEdit(self.groupBox_in)
        self.lineEdit_Q.setObjectName(u"lineEdit_Q")
        self.lineEdit_Q.setGeometry(QRect(210, 75, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_Q.sizePolicy().hasHeightForWidth())
        self.lineEdit_Q.setSizePolicy(sizePolicy)
        self.lineEdit_Q.setMinimumSize(QSize(0, 0))
        self.lineEdit_Q.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_Q.setBaseSize(QSize(0, 0))
        self.comboBox_S_or_UA = QComboBox(self.groupBox_in)
        self.comboBox_S_or_UA.addItem("")
        self.comboBox_S_or_UA.addItem("")
        self.comboBox_S_or_UA.setObjectName(u"comboBox_S_or_UA")
        self.comboBox_S_or_UA.setGeometry(QRect(10, 100, 181, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.comboBox_S_or_UA.sizePolicy().hasHeightForWidth())
        self.comboBox_S_or_UA.setSizePolicy(sizePolicy1)
        self.comboBox_S_or_UA.setMinimumSize(QSize(0, 0))
        self.comboBox_S_or_UA.setMaximumSize(QSize(9999, 9999))
        self.label_23 = QLabel(self.groupBox_in)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 75, 181, 21))
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QSize(0, 0))
        self.label_23.setMaximumSize(QSize(9999, 9999))
        self.label_26 = QLabel(self.groupBox_in)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 50, 181, 21))
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QSize(0, 0))
        self.label_26.setMaximumSize(QSize(9999, 9999))
        self.label_30 = QLabel(self.groupBox_in)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 25, 181, 21))
        self.label_30.setMinimumSize(QSize(0, 0))
        self.label_30.setMaximumSize(QSize(9999, 9999))
        self.groupBox_out = QGroupBox(self.centralwidget)
        self.groupBox_out.setObjectName(u"groupBox_out")
        self.groupBox_out.setGeometry(QRect(415, 435, 396, 106))
        self.lineEdit_out_Phi = QLineEdit(self.groupBox_out)
        self.lineEdit_out_Phi.setObjectName(u"lineEdit_out_Phi")
        self.lineEdit_out_Phi.setGeometry(QRect(210, 25, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_Phi.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Phi.setSizePolicy(sizePolicy)
        self.lineEdit_out_Phi.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_Phi.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_out_q = QLineEdit(self.groupBox_out)
        self.lineEdit_out_q.setObjectName(u"lineEdit_out_q")
        self.lineEdit_out_q.setGeometry(QRect(210, 50, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_q.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_q.setSizePolicy(sizePolicy)
        self.lineEdit_out_q.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_q.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_out_S_or_UA = QLineEdit(self.groupBox_out)
        self.lineEdit_out_S_or_UA.setObjectName(u"lineEdit_out_S_or_UA")
        self.lineEdit_out_S_or_UA.setGeometry(QRect(210, 75, 91, 21))
        sizePolicy.setHeightForWidth(self.lineEdit_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_S_or_UA.setSizePolicy(sizePolicy)
        self.lineEdit_out_S_or_UA.setMinimumSize(QSize(0, 0))
        self.lineEdit_out_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_Phi = QLabel(self.groupBox_out)
        self.label_out_Phi.setObjectName(u"label_out_Phi")
        self.label_out_Phi.setGeometry(QRect(10, 25, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_Phi.sizePolicy().hasHeightForWidth())
        self.label_out_Phi.setSizePolicy(sizePolicy)
        self.label_out_Phi.setMinimumSize(QSize(40, 0))
        self.label_out_Phi.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_q = QLabel(self.groupBox_out)
        self.label_out_q.setObjectName(u"label_out_q")
        self.label_out_q.setGeometry(QRect(10, 50, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_q.sizePolicy().hasHeightForWidth())
        self.label_out_q.setSizePolicy(sizePolicy)
        self.label_out_q.setMinimumSize(QSize(20, 0))
        self.label_out_q.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_S_or_UA = QLabel(self.groupBox_out)
        self.label_out_S_or_UA.setObjectName(u"label_out_S_or_UA")
        self.label_out_S_or_UA.setGeometry(QRect(10, 75, 181, 21))
        sizePolicy.setHeightForWidth(self.label_out_S_or_UA.sizePolicy().hasHeightForWidth())
        self.label_out_S_or_UA.setSizePolicy(sizePolicy)
        self.label_out_S_or_UA.setMinimumSize(QSize(20, 0))
        self.label_out_S_or_UA.setMaximumSize(QSize(16777215, 16777215))
        self.label_out_q_unit = QLabel(self.groupBox_out)
        self.label_out_q_unit.setObjectName(u"label_out_q_unit")
        self.label_out_q_unit.setGeometry(QRect(315, 50, 40, 21))
        self.label_out_S_or_UA_unit = QLabel(self.groupBox_out)
        self.label_out_S_or_UA_unit.setObjectName(u"label_out_S_or_UA_unit")
        self.label_out_S_or_UA_unit.setGeometry(QRect(315, 75, 40, 21))
        self.pushButton_calculate = QPushButton(self.centralwidget)
        self.pushButton_calculate.setObjectName(u"pushButton_calculate")
        self.pushButton_calculate.setGeometry(QRect(715, 555, 96, 26))
        self.pushButton_test = QPushButton(self.centralwidget)
        self.pushButton_test.setObjectName(u"pushButton_test")
        self.pushButton_test.setGeometry(QRect(600, 555, 96, 26))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 826, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.lineEdit_W, self.lineEdit_H)
        QWidget.setTabOrder(self.lineEdit_H, self.lineEdit_Q)
        QWidget.setTabOrder(self.lineEdit_Q, self.comboBox_S_or_UA)
        QWidget.setTabOrder(self.comboBox_S_or_UA, self.lineEdit_S_or_UA)
        QWidget.setTabOrder(self.lineEdit_S_or_UA, self.lineEdit_out_Phi)
        QWidget.setTabOrder(self.lineEdit_out_Phi, self.lineEdit_out_q)
        QWidget.setTabOrder(self.lineEdit_out_q, self.lineEdit_out_S_or_UA)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.groupBox_in.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.label_unit_S_or_UA.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"kW/m\u00b2", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"m", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_W.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_W.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_H.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_H.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_S_or_UA.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_S_or_UA.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.lineEdit_Q.setToolTip(QCoreApplication.translate("MainWindow", u"Positive float. {'Reduced fire load': 84, 'Normal fire load': 168}.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_Q.setStatusTip(QCoreApplication.translate("MainWindow", u"Positive float. {'Reduced fire load': 84, 'Normal fire load': 168}.", None))
#endif // QT_CONFIG(statustip)
        self.comboBox_S_or_UA.setItemText(0, QCoreApplication.translate("MainWindow", u"\u00bdS, emitter to boundary", None))
        self.comboBox_S_or_UA.setItemText(1, QCoreApplication.translate("MainWindow", u"Allowed unprotected area", None))

#if QT_CONFIG(tooltip)
        self.comboBox_S_or_UA.setToolTip(QCoreApplication.translate("MainWindow", u"This should be dealt within gui logic", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.comboBox_S_or_UA.setStatusTip(QCoreApplication.translate("MainWindow", u"This should be dealt within gui logic", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.label_23.setToolTip(QCoreApplication.translate("MainWindow", u"Emitter thermal heat flux.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_23.setStatusTip(QCoreApplication.translate("MainWindow", u"Emitter thermal heat flux.", None))
#endif // QT_CONFIG(statustip)
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Q, emitter heat flux", None))
#if QT_CONFIG(tooltip)
        self.label_26.setToolTip(QCoreApplication.translate("MainWindow", u"Height of emitter.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_26.setStatusTip(QCoreApplication.translate("MainWindow", u"Height of emitter.", None))
#endif // QT_CONFIG(statustip)
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"H, emitter height", None))
#if QT_CONFIG(tooltip)
        self.label_30.setToolTip(QCoreApplication.translate("MainWindow", u"Width of emitter.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_30.setStatusTip(QCoreApplication.translate("MainWindow", u"Width of emitter.", None))
#endif // QT_CONFIG(statustip)
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"W, emitter width", None))
        self.groupBox_out.setTitle(QCoreApplication.translate("MainWindow", u"Outputs", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_out_Phi.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_out_Phi.setToolTip(QCoreApplication.translate("MainWindow", u"Solved view factor.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_Phi.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved view factor.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_Phi.setText(QCoreApplication.translate("MainWindow", u"\u03a6, view factor", None))
#if QT_CONFIG(tooltip)
        self.label_out_q.setToolTip(QCoreApplication.translate("MainWindow", u"Solved heat flux at receiver surface when 100 % unprotected.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_q.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved heat flux at receiver surface when 100 % unprotected.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_q.setText(QCoreApplication.translate("MainWindow", u"q, receiver heat flux", None))
#if QT_CONFIG(tooltip)
        self.label_out_S_or_UA.setToolTip(QCoreApplication.translate("MainWindow", u"Solved maximum permissible unprotected area.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_out_S_or_UA.setStatusTip(QCoreApplication.translate("MainWindow", u"Solved maximum permissible unprotected area.", None))
#endif // QT_CONFIG(statustip)
        self.label_out_S_or_UA.setText(QCoreApplication.translate("MainWindow", u"Max. unprotected area", None))
        self.label_out_q_unit.setText(QCoreApplication.translate("MainWindow", u"kW/m\u00b2", None))
        self.label_out_S_or_UA_unit.setText(QCoreApplication.translate("MainWindow", u"%", None))
#if QT_CONFIG(tooltip)
        self.pushButton_calculate.setToolTip(QCoreApplication.translate("MainWindow", u"Calculate or press Enter.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_calculate.setStatusTip(QCoreApplication.translate("MainWindow", u"Calculate or press Enter.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_calculate.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
#if QT_CONFIG(tooltip)
        self.pushButton_test.setToolTip(QCoreApplication.translate("MainWindow", u"Generate example input parameters.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_test.setStatusTip(QCoreApplication.translate("MainWindow", u"Generate example input parameters.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_test.setText(QCoreApplication.translate("MainWindow", u"Example", None))
    # retranslateUi

