# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0103_merging_flow.ui',
# licensing of '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0103_merging_flow.ui' applies.
#
# Created: Thu Feb 20 22:28:39 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_figure_main = QtWidgets.QLabel(self.centralwidget)
        self.label_figure_main.setGeometry(QtCore.QRect(15, 15, 796, 566))
        self.label_figure_main.setText("")
        self.label_figure_main.setPixmap(QtGui.QPixmap("../../../../../../../Library/Mobile Documents/6LVTQB9699~com~seriflabs~affinitydesigner/Documents/FSEUTIL/final/0103_bs9999_2017_merging_flow_794_560.png"))
        self.label_figure_main.setObjectName("label_figure_main")
        self.groupBox_inputs = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_inputs.setGeometry(QtCore.QRect(415, 230, 396, 206))
        self.groupBox_inputs.setObjectName("groupBox_inputs")
        self.label_in_D_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_D_unit.setGeometry(QtCore.QRect(315, 100, 66, 21))
        self.label_in_D_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_D_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_in_D_unit.setObjectName("label_in_D_unit")
        self.label_in_N_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_N_unit.setGeometry(QtCore.QRect(315, 150, 66, 21))
        self.label_in_N_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_N_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_in_N_unit.setObjectName("label_in_N_unit")
        self.label_in_S_dn_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_S_dn_unit.setGeometry(QtCore.QRect(315, 50, 66, 21))
        self.label_in_S_dn_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_S_dn_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_in_S_dn_unit.setObjectName("label_in_S_dn_unit")
        self.label_in_S_up = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_S_up.setGeometry(QtCore.QRect(315, 25, 66, 21))
        self.label_in_S_up.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_S_up.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_in_S_up.setObjectName("label_in_S_up")
        self.lineEdit_in_S_up = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_in_S_up.setGeometry(QtCore.QRect(210, 25, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_S_up.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_S_up.setSizePolicy(sizePolicy)
        self.lineEdit_in_S_up.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_S_up.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_S_up.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_S_up.setObjectName("lineEdit_in_S_up")
        self.lineEdit_in_S_dn = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_in_S_dn.setGeometry(QtCore.QRect(210, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_S_dn.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_S_dn.setSizePolicy(sizePolicy)
        self.lineEdit_in_S_dn.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_S_dn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_S_dn.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_S_dn.setObjectName("lineEdit_in_S_dn")
        self.lineEdit_in_D = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_in_D.setGeometry(QtCore.QRect(210, 100, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_D.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_D.setSizePolicy(sizePolicy)
        self.lineEdit_in_D.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_D.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_D.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_D.setText("")
        self.lineEdit_in_D.setObjectName("lineEdit_in_D")
        self.lineEdit_in_N = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_in_N.setGeometry(QtCore.QRect(210, 150, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_N.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_N.setSizePolicy(sizePolicy)
        self.lineEdit_in_N.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_N.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_N.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_N.setText("")
        self.lineEdit_in_N.setObjectName("lineEdit_in_N")
        self.label_in_N = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_N.setGeometry(QtCore.QRect(10, 150, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in_N.sizePolicy().hasHeightForWidth())
        self.label_in_N.setSizePolicy(sizePolicy)
        self.label_in_N.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_N.setMaximumSize(QtCore.QSize(999999, 30))
        self.label_in_N.setObjectName("label_in_N")
        self.label_in_S_dn = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_S_dn.setGeometry(QtCore.QRect(10, 50, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in_S_dn.sizePolicy().hasHeightForWidth())
        self.label_in_S_dn.setSizePolicy(sizePolicy)
        self.label_in_S_dn.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_S_dn.setMaximumSize(QtCore.QSize(999999, 30))
        self.label_in_S_dn.setObjectName("label_in_S_dn")
        self.label_in_S_up_label = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_S_up_label.setGeometry(QtCore.QRect(10, 25, 181, 21))
        self.label_in_S_up_label.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_S_up_label.setMaximumSize(QtCore.QSize(999999, 30))
        self.label_in_S_up_label.setObjectName("label_in_S_up_label")
        self.label_in_B = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_B.setGeometry(QtCore.QRect(10, 125, 181, 21))
        self.label_in_B.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_B.setMaximumSize(QtCore.QSize(999999, 30))
        self.label_in_B.setObjectName("label_in_B")
        self.label_in_W_SE = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_W_SE.setGeometry(QtCore.QRect(10, 75, 181, 21))
        self.label_in_W_SE.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_W_SE.setMaximumSize(QtCore.QSize(999999, 30))
        self.label_in_W_SE.setObjectName("label_in_W_SE")
        self.lineEdit_in_B = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_in_B.setGeometry(QtCore.QRect(210, 125, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_B.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_B.setSizePolicy(sizePolicy)
        self.lineEdit_in_B.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_B.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_B.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_B.setObjectName("lineEdit_in_B")
        self.lineEdit_in_W_SE = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_in_W_SE.setGeometry(QtCore.QRect(210, 75, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_W_SE.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_W_SE.setSizePolicy(sizePolicy)
        self.lineEdit_in_W_SE.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_W_SE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_W_SE.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_W_SE.setText("")
        self.lineEdit_in_W_SE.setObjectName("lineEdit_in_W_SE")
        self.label_in_B_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_B_unit.setGeometry(QtCore.QRect(315, 125, 66, 21))
        self.label_in_B_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_B_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_in_B_unit.setObjectName("label_in_B_unit")
        self.label_in_W_SE_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_W_SE_unit.setGeometry(QtCore.QRect(315, 75, 66, 21))
        self.label_in_W_SE_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_W_SE_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_in_W_SE_unit.setObjectName("label_in_W_SE_unit")
        self.label_27 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_27.setGeometry(QtCore.QRect(10, 100, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 0))
        self.label_27.setMaximumSize(QtCore.QSize(999999, 30))
        self.label_27.setObjectName("label_27")
        self.lineEdit_in_X = QtWidgets.QLineEdit(self.groupBox_inputs)
        self.lineEdit_in_X.setGeometry(QtCore.QRect(210, 175, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_X.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_X.setSizePolicy(sizePolicy)
        self.lineEdit_in_X.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_X.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_X.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_X.setText("")
        self.lineEdit_in_X.setObjectName("lineEdit_in_X")
        self.label_in_X_unit = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_in_X_unit.setGeometry(QtCore.QRect(315, 175, 66, 21))
        self.label_in_X_unit.setMinimumSize(QtCore.QSize(0, 0))
        self.label_in_X_unit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_in_X_unit.setObjectName("label_in_X_unit")
        self.label_28 = QtWidgets.QLabel(self.groupBox_inputs)
        self.label_28.setGeometry(QtCore.QRect(10, 175, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_28.setMaximumSize(QtCore.QSize(999999, 30))
        self.label_28.setObjectName("label_28")
        self.groupBox_outputs = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_outputs.setGeometry(QtCore.QRect(415, 450, 391, 81))
        self.groupBox_outputs.setObjectName("groupBox_outputs")
        self.lineEdit_out_W_FE = QtWidgets.QLineEdit(self.groupBox_outputs)
        self.lineEdit_out_W_FE.setGeometry(QtCore.QRect(210, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_W_FE.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_W_FE.setSizePolicy(sizePolicy)
        self.lineEdit_out_W_FE.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_W_FE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_out_W_FE.setObjectName("lineEdit_out_W_FE")
        self.label_12 = QtWidgets.QLabel(self.groupBox_outputs)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(20, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setObjectName("label_12")
        self.label_25 = QtWidgets.QLabel(self.groupBox_outputs)
        self.label_25.setGeometry(QtCore.QRect(315, 50, 51, 21))
        self.label_25.setObjectName("label_25")
        self.checkBox_out_check = QtWidgets.QCheckBox(self.groupBox_outputs)
        self.checkBox_out_check.setGeometry(QtCore.QRect(10, 25, 371, 21))
        self.checkBox_out_check.setObjectName("checkBox_out_check")
        self.groupBox_options = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_options.setGeometry(QtCore.QRect(415, 115, 396, 101))
        self.groupBox_options.setObjectName("groupBox_options")
        self.radioButton_opt_scenario_1 = QtWidgets.QRadioButton(self.groupBox_options)
        self.radioButton_opt_scenario_1.setGeometry(QtCore.QRect(15, 25, 356, 18))
        self.radioButton_opt_scenario_1.setObjectName("radioButton_opt_scenario_1")
        self.radioButton_opt_scenario_2 = QtWidgets.QRadioButton(self.groupBox_options)
        self.radioButton_opt_scenario_2.setGeometry(QtCore.QRect(15, 50, 351, 18))
        self.radioButton_opt_scenario_2.setObjectName("radioButton_opt_scenario_2")
        self.radioButton_opt_scenario_3 = QtWidgets.QRadioButton(self.groupBox_options)
        self.radioButton_opt_scenario_3.setGeometry(QtCore.QRect(15, 75, 361, 18))
        self.radioButton_opt_scenario_3.setObjectName("radioButton_opt_scenario_3")
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_test.setGeometry(QtCore.QRect(600, 555, 96, 26))
        self.pushButton_test.setObjectName("pushButton_test")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(715, 555, 96, 26))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_opt_scenario_1, self.radioButton_opt_scenario_2)
        MainWindow.setTabOrder(self.radioButton_opt_scenario_2, self.radioButton_opt_scenario_3)
        MainWindow.setTabOrder(self.radioButton_opt_scenario_3, self.lineEdit_in_S_up)
        MainWindow.setTabOrder(self.lineEdit_in_S_up, self.lineEdit_in_S_dn)
        MainWindow.setTabOrder(self.lineEdit_in_S_dn, self.lineEdit_in_W_SE)
        MainWindow.setTabOrder(self.lineEdit_in_W_SE, self.lineEdit_in_D)
        MainWindow.setTabOrder(self.lineEdit_in_D, self.lineEdit_in_B)
        MainWindow.setTabOrder(self.lineEdit_in_B, self.lineEdit_in_N)
        MainWindow.setTabOrder(self.lineEdit_in_N, self.lineEdit_in_X)
        MainWindow.setTabOrder(self.lineEdit_in_X, self.checkBox_out_check)
        MainWindow.setTabOrder(self.checkBox_out_check, self.lineEdit_out_W_FE)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_inputs.setTitle(QtWidgets.QApplication.translate("MainWindow", "Inputs", None, -1))
        self.label_in_D_unit.setText(QtWidgets.QApplication.translate("MainWindow", "m", None, -1))
        self.label_in_N_unit.setText(QtWidgets.QApplication.translate("MainWindow", "person", None, -1))
        self.label_in_S_dn_unit.setText(QtWidgets.QApplication.translate("MainWindow", "mm", None, -1))
        self.label_in_S_up.setText(QtWidgets.QApplication.translate("MainWindow", "mm", None, -1))
        self.lineEdit_in_S_up.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_S_up.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_S_dn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_S_dn.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_D.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_N.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_N.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.label_in_N.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Number of persons from ground level.", None, -1))
        self.label_in_N.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Number of persons from ground level.", None, -1))
        self.label_in_N.setText(QtWidgets.QApplication.translate("MainWindow", "N, no. persons from ext. lev.", None, -1))
        self.label_in_S_dn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Width of the stair to lower (basement) levels.", None, -1))
        self.label_in_S_dn.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Width of the stair to lower (basement) levels.", None, -1))
        self.label_in_S_dn.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>S<span style=\" vertical-align:sub;\">dn</span>, stair width to lower levels</p></body></html>", None, -1))
        self.label_in_S_up_label.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Width of the stair to upper levels.", None, -1))
        self.label_in_S_up_label.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Width of the stair to upper levels.", None, -1))
        self.label_in_S_up_label.setText(QtWidgets.QApplication.translate("MainWindow", "S<sub>up</sub>, stair width to upper level(s)", None, -1))
        self.label_in_B.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Number of persons from lower (basement) level.", None, -1))
        self.label_in_B.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Number of persons from lower (basement) level.", None, -1))
        self.label_in_B.setText(QtWidgets.QApplication.translate("MainWindow", "B, no. persons from lower lev.", None, -1))
        self.label_in_W_SE.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Width of the door from ground floor level.", None, -1))
        self.label_in_W_SE.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Width of the door from ground floor level.", None, -1))
        self.label_in_W_SE.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>W<span style=\" vertical-align:sub;\">SE</span>, door width from final exit level</p></body></html>", None, -1))
        self.lineEdit_in_B.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_B.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_W_SE.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_W_SE.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.label_in_B_unit.setText(QtWidgets.QApplication.translate("MainWindow", "mm", None, -1))
        self.label_in_W_SE_unit.setText(QtWidgets.QApplication.translate("MainWindow", "mm", None, -1))
        self.label_27.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Distance between building final exit to door of ground level or lower stair.", None, -1))
        self.label_27.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Distance between building final exit to door of ground level or lower stair.", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "D, distance indicated points", None, -1))
        self.lineEdit_in_X.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.lineEdit_in_X.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Positive float.", None, -1))
        self.label_in_X_unit.setText(QtWidgets.QApplication.translate("MainWindow", "mm/pers.", None, -1))
        self.label_28.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Minimum door width per person.", None, -1))
        self.label_28.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Minimum door width per person.", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "X, exit factor", None, -1))
        self.groupBox_outputs.setTitle(QtWidgets.QApplication.translate("MainWindow", "Outputs", None, -1))
        self.label_12.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved flame height.", None, -1))
        self.label_12.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Solved flame height.", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>W<span style=\" vertical-align:sub;\">FE</span>, calculated final exit width</p></body></html>", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "mm", None, -1))
        self.checkBox_out_check.setText(QtWidgets.QApplication.translate("MainWindow", "Check if \"(B+N)>60 and D<2\" is True.", None, -1))
        self.groupBox_options.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.radioButton_opt_scenario_1.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Scenario 1. Building final exit serves flow from upper levels and ground level.", None, -1))
        self.radioButton_opt_scenario_1.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Scenario 1. Building final exit serves flow from upper levels and ground level.", None, -1))
        self.radioButton_opt_scenario_1.setText(QtWidgets.QApplication.translate("MainWindow", "Scenario 1. Flow from upper and final exit levels.", None, -1))
        self.radioButton_opt_scenario_2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Scenario 2. Building final exit serves flow from upper levels and lower (basement) levels.", None, -1))
        self.radioButton_opt_scenario_2.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Scenario 2. Building final exit serves flow from upper levels and lower (basement) levels.", None, -1))
        self.radioButton_opt_scenario_2.setText(QtWidgets.QApplication.translate("MainWindow", "Scenario 2. Flow from upper and basement levels.", None, -1))
        self.radioButton_opt_scenario_3.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Scenario 3. Building final exit serves flow from upper levels, lower (basement) levels and ground level.", None, -1))
        self.radioButton_opt_scenario_3.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Scenario 3. Building final exit serves flow from upper levels, lower (basement) levels and ground level.", None, -1))
        self.radioButton_opt_scenario_3.setText(QtWidgets.QApplication.translate("MainWindow", "Scenario 3. Flow from upper, lower and final exit levels.", None, -1))
        self.pushButton_test.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Generate example input parameters.", None, -1))
        self.pushButton_test.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Generate example input parameters.", None, -1))
        self.pushButton_test.setText(QtWidgets.QApplication.translate("MainWindow", "Example", None, -1))
        self.pushButton_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))

