# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0405_thermal_radiation_extreme.ui',
# licensing of '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/dialog_0405_thermal_radiation_extreme.ui' applies.
#
# Created: Thu Feb 20 22:28:39 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 401)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 310, 786, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_in = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_in.setGeometry(QtCore.QRect(370, 40, 201, 251))
        self.groupBox_in.setObjectName("groupBox_in")
        self.label_30 = QtWidgets.QLabel(self.groupBox_in)
        self.label_30.setGeometry(QtCore.QRect(10, 75, 61, 21))
        self.label_30.setMinimumSize(QtCore.QSize(0, 0))
        self.label_30.setMaximumSize(QtCore.QSize(99999, 99999))
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_24 = QtWidgets.QLabel(self.groupBox_in)
        self.label_24.setGeometry(QtCore.QRect(10, 220, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        self.label_24.setMaximumSize(QtCore.QSize(99999, 99999))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.groupBox_in)
        self.label_26.setGeometry(QtCore.QRect(10, 145, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 0))
        self.label_26.setMaximumSize(QtCore.QSize(99999, 99999))
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.lineEdit_in_receiver_location = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_in_receiver_location.setGeometry(QtCore.QRect(70, 170, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_receiver_location.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_receiver_location.setSizePolicy(sizePolicy)
        self.lineEdit_in_receiver_location.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_receiver_location.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_receiver_location.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_receiver_location.setObjectName("lineEdit_in_receiver_location")
        self.lineEdit_in_emitter_normal = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_in_emitter_normal.setGeometry(QtCore.QRect(70, 145, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_emitter_normal.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_emitter_normal.setSizePolicy(sizePolicy)
        self.lineEdit_in_emitter_normal.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_emitter_normal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_emitter_normal.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_emitter_normal.setText("")
        self.lineEdit_in_emitter_normal.setObjectName("lineEdit_in_emitter_normal")
        self.lineEdit_in_receiver_normal = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_in_receiver_normal.setGeometry(QtCore.QRect(70, 195, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_receiver_normal.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_receiver_normal.setSizePolicy(sizePolicy)
        self.lineEdit_in_receiver_normal.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_receiver_normal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_receiver_normal.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_receiver_normal.setObjectName("lineEdit_in_receiver_normal")
        self.label_43 = QtWidgets.QLabel(self.groupBox_in)
        self.label_43.setGeometry(QtCore.QRect(140, 220, 40, 21))
        self.label_43.setMinimumSize(QtCore.QSize(0, 0))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_43.setObjectName("label_43")
        self.lineEdit_in_Q = QtWidgets.QLineEdit(self.groupBox_in)
        self.lineEdit_in_Q.setGeometry(QtCore.QRect(70, 220, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_Q.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_Q.setSizePolicy(sizePolicy)
        self.lineEdit_in_Q.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_Q.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_in_Q.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_in_Q.setObjectName("lineEdit_in_Q")
        self.label_27 = QtWidgets.QLabel(self.groupBox_in)
        self.label_27.setGeometry(QtCore.QRect(10, 195, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 0))
        self.label_27.setMaximumSize(QtCore.QSize(99999, 99999))
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_in)
        self.label_28.setGeometry(QtCore.QRect(10, 170, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_28.setMaximumSize(QtCore.QSize(99999, 99999))
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.plainTextEdit_in_emiter_xyz = QtWidgets.QPlainTextEdit(self.groupBox_in)
        self.plainTextEdit_in_emiter_xyz.setGeometry(QtCore.QRect(70, 25, 121, 116))
        self.plainTextEdit_in_emiter_xyz.setObjectName("plainTextEdit_in_emiter_xyz")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 15, 341, 285))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/phi_calculator_extreme.png"))
        self.label.setObjectName("label")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(675, 330, 96, 24))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.groupBox_optionals = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_optionals.setGeometry(QtCore.QRect(585, 40, 186, 86))
        self.groupBox_optionals.setObjectName("groupBox_optionals")
        self.lineEdit_in_emitter_points = QtWidgets.QLineEdit(self.groupBox_optionals)
        self.lineEdit_in_emitter_points.setGeometry(QtCore.QRect(70, 25, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_emitter_points.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_emitter_points.setSizePolicy(sizePolicy)
        self.lineEdit_in_emitter_points.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_emitter_points.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_emitter_points.setObjectName("lineEdit_in_emitter_points")
        self.label_14 = QtWidgets.QLabel(self.groupBox_optionals)
        self.label_14.setGeometry(QtCore.QRect(10, 25, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(40, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_optionals)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(40, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_15.setObjectName("label_15")
        self.lineEdit_in_receiver_initial_temperature = QtWidgets.QLineEdit(self.groupBox_optionals)
        self.lineEdit_in_receiver_initial_temperature.setGeometry(QtCore.QRect(70, 50, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_in_receiver_initial_temperature.sizePolicy().hasHeightForWidth())
        self.lineEdit_in_receiver_initial_temperature.setSizePolicy(sizePolicy)
        self.lineEdit_in_receiver_initial_temperature.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_in_receiver_initial_temperature.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_in_receiver_initial_temperature.setObjectName("lineEdit_in_receiver_initial_temperature")
        self.label_45 = QtWidgets.QLabel(self.groupBox_optionals)
        self.label_45.setGeometry(QtCore.QRect(135, 50, 50, 21))
        self.label_45.setObjectName("label_45")
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_test.setGeometry(QtCore.QRect(15, 330, 96, 24))
        self.pushButton_test.setObjectName("pushButton_test")
        self.groupBox_out = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_out.setGeometry(QtCore.QRect(585, 185, 186, 106))
        self.groupBox_out.setObjectName("groupBox_out")
        self.lineEdit_out_Phi = QtWidgets.QLineEdit(self.groupBox_out)
        self.lineEdit_out_Phi.setGeometry(QtCore.QRect(70, 50, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_Phi.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_Phi.setSizePolicy(sizePolicy)
        self.lineEdit_out_Phi.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_Phi.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_out_Phi.setObjectName("lineEdit_out_Phi")
        self.lineEdit_out_q = QtWidgets.QLineEdit(self.groupBox_out)
        self.lineEdit_out_q.setGeometry(QtCore.QRect(70, 75, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_q.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_q.setSizePolicy(sizePolicy)
        self.lineEdit_out_q.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_q.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_out_q.setObjectName("lineEdit_out_q")
        self.label_out_Phi = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_Phi.setGeometry(QtCore.QRect(10, 50, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_Phi.sizePolicy().hasHeightForWidth())
        self.label_out_Phi.setSizePolicy(sizePolicy)
        self.label_out_Phi.setMinimumSize(QtCore.QSize(40, 0))
        self.label_out_Phi.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_out_Phi.setObjectName("label_out_Phi")
        self.label_out_q = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_q.setGeometry(QtCore.QRect(10, 75, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_q.sizePolicy().hasHeightForWidth())
        self.label_out_q.setSizePolicy(sizePolicy)
        self.label_out_q.setMinimumSize(QtCore.QSize(20, 0))
        self.label_out_q.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_out_q.setObjectName("label_out_q")
        self.label_out_q_unit = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_q_unit.setGeometry(QtCore.QRect(135, 75, 50, 21))
        self.label_out_q_unit.setObjectName("label_out_q_unit")
        self.label_out_T = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_T.setGeometry(QtCore.QRect(10, 25, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_out_T.sizePolicy().hasHeightForWidth())
        self.label_out_T.setSizePolicy(sizePolicy)
        self.label_out_T.setMinimumSize(QtCore.QSize(40, 0))
        self.label_out_T.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_out_T.setObjectName("label_out_T")
        self.lineEdit_out_T = QtWidgets.QLineEdit(self.groupBox_out)
        self.lineEdit_out_T.setGeometry(QtCore.QRect(70, 25, 60, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_T.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_T.setSizePolicy(sizePolicy)
        self.lineEdit_out_T.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_out_T.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_out_T.setObjectName("lineEdit_out_T")
        self.label_out_T_unit = QtWidgets.QLabel(self.groupBox_out)
        self.label_out_T_unit.setGeometry(QtCore.QRect(135, 25, 50, 21))
        self.label_out_T_unit.setObjectName("label_out_T_unit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_in.setTitle(QtWidgets.QApplication.translate("MainWindow", "Inputs", None, -1))
        self.label_30.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Vertices of emitter", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "XYZ", None, -1))
        self.label_24.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Heat flux of emitter", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Q", None, -1))
        self.label_26.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Emitter orientation (normal)", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">nE</span>, Y<span style=\" vertical-align:sub;\">nE</span>, Z<span style=\" vertical-align:sub;\">nE</span></p></body></html>", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "kW/m²", None, -1))
        self.label_27.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Receiver orientation (normal)", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">nR</span>, Y<span style=\" vertical-align:sub;\">nR</span>, Z<span style=\" vertical-align:sub;\">nR</span></p></body></html>", None, -1))
        self.label_28.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Receiver location", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">R</span>, Y<span style=\" vertical-align:sub;\">R</span>, Z<span style=\" vertical-align:sub;\">R</span></p></body></html>", None, -1))
        self.pushButton_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.groupBox_optionals.setTitle(QtWidgets.QApplication.translate("MainWindow", "Optional", None, -1))
        self.label_14.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Number of emitting points on emitter surface that the calculation will be based on", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "n. points", None, -1))
        self.label_15.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Receiver temperature (i.e. ambient temperature)", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "T receiver", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "K", None, -1))
        self.pushButton_test.setText(QtWidgets.QApplication.translate("MainWindow", "Example", None, -1))
        self.groupBox_out.setTitle(QtWidgets.QApplication.translate("MainWindow", "Outputs", None, -1))
        self.label_out_Phi.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved view factor", None, -1))
        self.label_out_Phi.setText(QtWidgets.QApplication.translate("MainWindow", "Φ", None, -1))
        self.label_out_q.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved heat flux at receiver", None, -1))
        self.label_out_q.setText(QtWidgets.QApplication.translate("MainWindow", "q", None, -1))
        self.label_out_q_unit.setText(QtWidgets.QApplication.translate("MainWindow", "kW/m²", None, -1))
        self.label_out_T.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Solved temperature at receiver", None, -1))
        self.label_out_T.setText(QtWidgets.QApplication.translate("MainWindow", "T", None, -1))
        self.label_out_T_unit.setText(QtWidgets.QApplication.translate("MainWindow", "K", None, -1))

