# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/main.ui',
# licensing of '/Users/ian/Documents/GitHub/fsetools/fsetools/gui/layout/ui/main.ui' applies.
#
# Created: Thu Feb 20 22:28:39 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 507)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(15, 110, 381, 106))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_0102_bs9999_datasheet_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_0102_bs9999_datasheet_1.setGeometry(QtCore.QRect(85, 20, 70, 70))
        self.pushButton_0102_bs9999_datasheet_1.setObjectName("pushButton_0102_bs9999_datasheet_1")
        self.pushButton_0103_merging_flow = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_0103_merging_flow.setEnabled(True)
        self.pushButton_0103_merging_flow.setGeometry(QtCore.QRect(155, 20, 70, 70))
        self.pushButton_0103_merging_flow.setObjectName("pushButton_0103_merging_flow")
        self.pushButton_0111_heat_detector_activation = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_0111_heat_detector_activation.setGeometry(QtCore.QRect(225, 20, 70, 70))
        self.pushButton_0111_heat_detector_activation.setObjectName("pushButton_0111_heat_detector_activation")
        self.b4_01_br187_parallel_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.b4_01_br187_parallel_10.setEnabled(False)
        self.b4_01_br187_parallel_10.setGeometry(QtCore.QRect(295, 20, 70, 70))
        self.b4_01_br187_parallel_10.setObjectName("b4_01_br187_parallel_10")
        self.pushButton_0101_adb2_datasheet_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_0101_adb2_datasheet_1.setGeometry(QtCore.QRect(15, 20, 70, 70))
        self.pushButton_0101_adb2_datasheet_1.setObjectName("pushButton_0101_adb2_datasheet_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(15, 340, 311, 106))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_0601_naming_convention = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_0601_naming_convention.setGeometry(QtCore.QRect(15, 20, 70, 70))
        self.pushButton_0601_naming_convention.setObjectName("pushButton_0601_naming_convention")
        self.b4_01_br187_parallel_11 = QtWidgets.QPushButton(self.groupBox_2)
        self.b4_01_br187_parallel_11.setEnabled(False)
        self.b4_01_br187_parallel_11.setGeometry(QtCore.QRect(85, 20, 70, 70))
        self.b4_01_br187_parallel_11.setObjectName("b4_01_br187_parallel_11")
        self.b4_01_br187_parallel_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.b4_01_br187_parallel_12.setEnabled(False)
        self.b4_01_br187_parallel_12.setGeometry(QtCore.QRect(155, 20, 70, 70))
        self.b4_01_br187_parallel_12.setObjectName("b4_01_br187_parallel_12")
        self.pushButton_0602_pd7974_flame_height = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_0602_pd7974_flame_height.setGeometry(QtCore.QRect(225, 20, 70, 70))
        self.pushButton_0602_pd7974_flame_height.setObjectName("pushButton_0602_pd7974_flame_height")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(15, 225, 381, 106))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_0401_br187_parallel_simple = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_0401_br187_parallel_simple.setGeometry(QtCore.QRect(15, 20, 70, 70))
        self.pushButton_0401_br187_parallel_simple.setObjectName("pushButton_0401_br187_parallel_simple")
        self.pushButton_0402_br187_perpendicular_simple = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_0402_br187_perpendicular_simple.setGeometry(QtCore.QRect(85, 20, 70, 70))
        self.pushButton_0402_br187_perpendicular_simple.setObjectName("pushButton_0402_br187_perpendicular_simple")
        self.pushButton_0403_br187_parallel_complex = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_0403_br187_parallel_complex.setGeometry(QtCore.QRect(155, 20, 70, 70))
        self.pushButton_0403_br187_parallel_complex.setObjectName("pushButton_0403_br187_parallel_complex")
        self.pushButton_0404_br187_perpendicular_complex = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_0404_br187_perpendicular_complex.setGeometry(QtCore.QRect(225, 20, 70, 70))
        self.pushButton_0404_br187_perpendicular_complex.setObjectName("pushButton_0404_br187_perpendicular_complex")
        self.pushButton_0405_thermal_radiation_extreme = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_0405_thermal_radiation_extreme.setEnabled(True)
        self.pushButton_0405_thermal_radiation_extreme.setGeometry(QtCore.QRect(295, 20, 70, 70))
        self.pushButton_0405_thermal_radiation_extreme.setObjectName("pushButton_0405_thermal_radiation_extreme")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(15, 15, 431, 84))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_big_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_big_name.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_big_name.setFont(font)
        self.label_big_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_big_name.setObjectName("label_big_name")
        self.verticalLayout.addWidget(self.label_big_name)
        self.label_copy_right = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_copy_right.setMinimumSize(QtCore.QSize(0, 28))
        self.label_copy_right.setWordWrap(True)
        self.label_copy_right.setObjectName("label_copy_right")
        self.verticalLayout.addWidget(self.label_copy_right)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_logo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_logo.setMinimumSize(QtCore.QSize(194, 80))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../images/OFR_LOGO_2_194_80.png"))
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout.addWidget(self.label_logo)
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setGeometry(QtCore.QRect(15, 450, 157, 14))
        self.label_version.setMinimumSize(QtCore.QSize(0, 14))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_version.setFont(font)
        self.label_version.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_0101_ADB_Vol_2_Datasheet = QtWidgets.QAction(MainWindow)
        self.action_0101_ADB_Vol_2_Datasheet.setObjectName("action_0101_ADB_Vol_2_Datasheet")
        self.action_0102_BS_9999_Datasheet = QtWidgets.QAction(MainWindow)
        self.action_0102_BS_9999_Datasheet.setObjectName("action_0102_BS_9999_Datasheet")
        self.action_0103_BS_9999_Merging_flow = QtWidgets.QAction(MainWindow)
        self.action_0103_BS_9999_Merging_flow.setObjectName("action_0103_BS_9999_Merging_flow")
        self.action_0104_PD_7974_HD_activation = QtWidgets.QAction(MainWindow)
        self.action_0104_PD_7974_HD_activation.setObjectName("action_0104_PD_7974_HD_activation")
        self.action_0401_BR_187_parallel_simple = QtWidgets.QAction(MainWindow)
        self.action_0401_BR_187_parallel_simple.setObjectName("action_0401_BR_187_parallel_simple")
        self.action_0402_BR_187_perpendicular_simple = QtWidgets.QAction(MainWindow)
        self.action_0402_BR_187_perpendicular_simple.setObjectName("action_0402_BR_187_perpendicular_simple")
        self.action_0403_BR_187_parallel_complex = QtWidgets.QAction(MainWindow)
        self.action_0403_BR_187_parallel_complex.setObjectName("action_0403_BR_187_parallel_complex")
        self.action_0404_BR_187_perpendicular_complex = QtWidgets.QAction(MainWindow)
        self.action_0404_BR_187_perpendicular_complex.setObjectName("action_0404_BR_187_perpendicular_complex")
        self.action_0601_OFR_naming_protocol = QtWidgets.QAction(MainWindow)
        self.action_0601_OFR_naming_protocol.setObjectName("action_0601_OFR_naming_protocol")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_0101_adb2_datasheet_1, self.pushButton_0102_bs9999_datasheet_1)
        MainWindow.setTabOrder(self.pushButton_0102_bs9999_datasheet_1, self.pushButton_0103_merging_flow)
        MainWindow.setTabOrder(self.pushButton_0103_merging_flow, self.pushButton_0111_heat_detector_activation)
        MainWindow.setTabOrder(self.pushButton_0111_heat_detector_activation, self.b4_01_br187_parallel_10)
        MainWindow.setTabOrder(self.b4_01_br187_parallel_10, self.pushButton_0401_br187_parallel_simple)
        MainWindow.setTabOrder(self.pushButton_0401_br187_parallel_simple, self.pushButton_0402_br187_perpendicular_simple)
        MainWindow.setTabOrder(self.pushButton_0402_br187_perpendicular_simple, self.pushButton_0403_br187_parallel_complex)
        MainWindow.setTabOrder(self.pushButton_0403_br187_parallel_complex, self.pushButton_0404_br187_perpendicular_complex)
        MainWindow.setTabOrder(self.pushButton_0404_br187_perpendicular_complex, self.pushButton_0601_naming_convention)
        MainWindow.setTabOrder(self.pushButton_0601_naming_convention, self.b4_01_br187_parallel_11)
        MainWindow.setTabOrder(self.b4_01_br187_parallel_11, self.b4_01_br187_parallel_12)

    def retranslateUi(self, MainWindow):
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "B1 Means of escape", None, -1))
        self.pushButton_0102_bs9999_datasheet_1.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Data sheet 1 for BS 9999:2017, for B1.", None, -1))
        self.pushButton_0102_bs9999_datasheet_1.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Data sheet 1 for BS 9999:2017, for B1.", None, -1))
        self.pushButton_0102_bs9999_datasheet_1.setText(QtWidgets.QApplication.translate("MainWindow", "BS 9999\n"
"Datasheet\n"
"No. 1", None, -1))
        self.pushButton_0103_merging_flow.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Merging flow calculation in accordance with BS 9999:2017.", None, -1))
        self.pushButton_0103_merging_flow.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Merging flow calculation in accordance with BS 9999:2017.", None, -1))
        self.pushButton_0103_merging_flow.setText(QtWidgets.QApplication.translate("MainWindow", "Merging\n"
"Flow", None, -1))
        self.pushButton_0111_heat_detector_activation.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Heat detector activation time (ceiling jet) in accordance with PD 7974-1:2019.", None, -1))
        self.pushButton_0111_heat_detector_activation.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Heat detector activation time (ceiling jet) in accordance with PD 7974-1:2019.", None, -1))
        self.pushButton_0111_heat_detector_activation.setText(QtWidgets.QApplication.translate("MainWindow", "PD 7974\n"
"HD\n"
"Activation\n"
"Time", None, -1))
        self.b4_01_br187_parallel_10.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Not implemented.", None, -1))
        self.b4_01_br187_parallel_10.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Not implemented.", None, -1))
        self.b4_01_br187_parallel_10.setText(QtWidgets.QApplication.translate("MainWindow", "Zone\n"
"Model", None, -1))
        self.pushButton_0101_adb2_datasheet_1.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Data sheet 1 for Approved Document B (2019) Vol. 2, for B1.", None, -1))
        self.pushButton_0101_adb2_datasheet_1.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Data sheet 1 for Approved Document B (2019) Vol. 2, for B1.", None, -1))
        self.pushButton_0101_adb2_datasheet_1.setText(QtWidgets.QApplication.translate("MainWindow", "ADB 2\n"
"Datasheet\n"
"No. 1", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Miscellaneous", None, -1))
        self.pushButton_0601_naming_convention.setToolTip(QtWidgets.QApplication.translate("MainWindow", "File name generator in accordance with OFR file naming protocal.", None, -1))
        self.pushButton_0601_naming_convention.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "File name generator in accordance with OFR file naming protocal.", None, -1))
        self.pushButton_0601_naming_convention.setText(QtWidgets.QApplication.translate("MainWindow", "File\n"
"Naming\n"
"Protocol", None, -1))
        self.b4_01_br187_parallel_11.setText(QtWidgets.QApplication.translate("MainWindow", "CFD\n"
"Required\n"
"Vent. Size", None, -1))
        self.b4_01_br187_parallel_12.setToolTip(QtWidgets.QApplication.translate("MainWindow", "To estimate optimal mesh resolution.", None, -1))
        self.b4_01_br187_parallel_12.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "To estimate optimal mesh resolution.", None, -1))
        self.b4_01_br187_parallel_12.setText(QtWidgets.QApplication.translate("MainWindow", "CFD\n"
"Mesh Size", None, -1))
        self.pushButton_0602_pd7974_flame_height.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Flame height in accordance with PD 7974-1:2019.", None, -1))
        self.pushButton_0602_pd7974_flame_height.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Flame height in accordance with PD 7974-1:2019.", None, -1))
        self.pushButton_0602_pd7974_flame_height.setText(QtWidgets.QApplication.translate("MainWindow", "PD 7974\n"
"Flame\n"
"Height", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "B4 External flame spread", None, -1))
        self.pushButton_0401_br187_parallel_simple.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Parallel rectangular orientation).", None, -1))
        self.pushButton_0401_br187_parallel_simple.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Parallel rectangular orientation).", None, -1))
        self.pushButton_0401_br187_parallel_simple.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187\n"
"Parallel", None, -1))
        self.pushButton_0402_br187_perpendicular_simple.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Perpendicular rectangular orientation).", None, -1))
        self.pushButton_0402_br187_perpendicular_simple.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Perpendicular rectangular orientation).", None, -1))
        self.pushButton_0402_br187_perpendicular_simple.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187\n"
"Perp.", None, -1))
        self.pushButton_0403_br187_parallel_complex.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Parallel rectangular orientation).", None, -1))
        self.pushButton_0403_br187_parallel_complex.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Parallel rectangular orientation).", None, -1))
        self.pushButton_0403_br187_parallel_complex.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187\n"
"Parallel 2", None, -1))
        self.pushButton_0404_br187_perpendicular_complex.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Perpendicular rectangular orientation).", None, -1))
        self.pushButton_0404_br187_perpendicular_complex.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Thermal radiation calculation following BR 187 (Perpendicular rectangular orientation).", None, -1))
        self.pushButton_0404_br187_perpendicular_complex.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187\n"
"Perp. 2", None, -1))
        self.pushButton_0405_thermal_radiation_extreme.setToolTip(QtWidgets.QApplication.translate("MainWindow", "General purpose thermal radiation calculator.", None, -1))
        self.pushButton_0405_thermal_radiation_extreme.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "General purpose thermal radiation calculator.", None, -1))
        self.pushButton_0405_thermal_radiation_extreme.setText(QtWidgets.QApplication.translate("MainWindow", "Therm. Rad.\n"
"Analysis", None, -1))
        self.label_big_name.setText(QtWidgets.QApplication.translate("MainWindow", "OFR TOOLBOX", None, -1))
        self.label_copy_right.setText(QtWidgets.QApplication.translate("MainWindow", "© OFR Consultants Ltd.\n"
"All rights reserved.", None, -1))
        self.label_version.setText(QtWidgets.QApplication.translate("MainWindow", "Version #.#.#", None, -1))
        self.action_0101_ADB_Vol_2_Datasheet.setText(QtWidgets.QApplication.translate("MainWindow", "ADB Vol. 2 Datasheet No. 1", None, -1))
        self.action_0102_BS_9999_Datasheet.setText(QtWidgets.QApplication.translate("MainWindow", "BS 9999 Datasheet No. 1", None, -1))
        self.action_0103_BS_9999_Merging_flow.setText(QtWidgets.QApplication.translate("MainWindow", "BS 9999 Merging flow calculation", None, -1))
        self.action_0104_PD_7974_HD_activation.setText(QtWidgets.QApplication.translate("MainWindow", "PD 7974 HD activation time calculation", None, -1))
        self.action_0401_BR_187_parallel_simple.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187 parallel plane calculation", None, -1))
        self.action_0402_BR_187_perpendicular_simple.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187 perpendicular plane calculation", None, -1))
        self.action_0403_BR_187_parallel_complex.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187 parallel plane calculation (complex)", None, -1))
        self.action_0404_BR_187_perpendicular_complex.setText(QtWidgets.QApplication.translate("MainWindow", "BR 187 perpendicular plain calculation (complex)", None, -1))
        self.action_0601_OFR_naming_protocol.setText(QtWidgets.QApplication.translate("MainWindow", "OFR file naming protocol", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

