from fseutil.libstd.pd_7974_1_2019 import _test_eq_10_virtual_origin as test_eq_10_virtual_origin
from fseutil.libstd.pd_7974_1_2019 import _test_eq_14_plume_temperature as test_eq_14_plume_temperature
from fseutil.libstd.pd_7974_1_2019 import _test_eq_15_plume_velocity as test_eq_15_plume_velocity
from fseutil.libstd.pd_7974_1_2019 import _test_eq_22_t_squared_fire_growth as test_eq_22_t_squared_fire_growth
from fseutil.libstd.pd_7974_1_2019 import _test_eq_26_axisymmetric_ceiling_jet_temperature as test_eq_26_axisymmetric_ceiling_jet_temperature
from fseutil.libstd.pd_7974_1_2019 import _test_eq_27_axisymmetric_ceiling_jet_velocity as test_eq_27_axisymmetric_ceiling_jet_velocity
from fseutil.libstd.pd_7974_1_2019 import _test_eq_55_activation_of_heat_detector_device as test_eq_55_activation_of_heat_detector_device

test_eq_10_virtual_origin()
test_eq_14_plume_temperature()
test_eq_15_plume_velocity()
test_eq_22_t_squared_fire_growth()
test_eq_26_axisymmetric_ceiling_jet_temperature()
test_eq_27_axisymmetric_ceiling_jet_velocity()
test_eq_55_activation_of_heat_detector_device()
